# Generated by Django 3.0.5 on 2020-06-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('menu', 'menu'), ('haber', 'haber'), ('duyuru', 'duyuru'), ('etkinlik', 'etkinlik')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
